### ISSUE TITLE
iOS: onDynamicLink is called only first time after app installed

### ISSUE THREAD

**Issue by prinstonjim** [chemerisuk/cordova-plugin-firebase-dynamiclinks#27]
iOS: onDynamicLink is called only first time after app installed, If I click the dynamic link then the onDynamicLink function is never called.

**Comment by csotomon** [comment]
I have the same problem with android

**Comment by hribab** [comment]
same problem

**Comment by kvindasAB** [comment]
+1

**Comment by kvindasAB** [comment]
Could this be related to an AppDelegate conflict? 
Im also using the FirebasePush notifications plugin.

**Comment by Upperfoot** [comment]
Same problem, any news on this? @chemerisuk

**Comment by kvindasAB** [comment]
For those interested, I switched from this project to a fork.

https://github.com/knil-public/cordova-plugin-firebase-dynamiclinks.git

This other fork works pretty well, is not perfect either, but at least regarding IOS works better than the current repo. On this other fork, I found that first time the IOS app is installed, the dynamic link handler is not called, besides that, the other scenarios work pretty well.

**Comment by Upperfoot** [comment]
Did a bit of digging, apparently the events get logged with Android (verified by ADB)

https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/blob/master/src/android/FirebaseDynamicLinksPlugin.java#L70-L72

It points towards the callback promise not being called again at all, subsequent calls to onDynamicLink return the updated link, it's as if Cordova is not triggering the callback.

My workaround, which is quite hacky is the following (typescript)

```
    timestamp: any = false;
    setup() {
        setInterval(() => {
            this.firebaseDynamicLinks.onDynamicLink()
                .then((res: any) => {
                    if(this.timestamp != res.clickTimestamp) {
                        this.processDynamicLink(res);
                        console.log(res);
                        this.timestamp = res.clickTimestamp;
                    }
                }) //Handle the logic here after opening the app with the Dynamic link
                .catch((error:any) => {

                });
        }, 500);
    }

```

What this does is essentially recall the onDynamicLink method to get a fresh copy of the result, and we compare against the click timestamp to make sure we don't open it multiple times (because of the setInterval).

**Comment by bhavinwebdesk** [comment]
@kvindasAB Is your solution working for you?

**Comment by chemerisuk** [comment]
Paste link to the Notes app and navigate from there
