### ISSUE TITLE
Testing in iOS app not in AppStore

### ISSUE THREAD

**Issue by silverio** [chemerisuk/cordova-plugin-firebase-dynamiclinks#41]
Hi guys am I am trying to test this plugin with an app under development which is not in the AppStore. I configured everything in the firebase console (I am using youtube's Appstore ID because my app isn't in the Appstore), and I am doing the following to test the dynamic links:

1. Delete the app from the device.
2. Use notes app to open dynamic link
3. In the preview page click open, then I am redirected to the Appstore (Youtube App).
4. Close appstore.
5. Install App and wait for the plugin response.

I configured the entitlements file with applinks:XXXX.app.goo.gl and the URL types with my bundle identifier. But I am not getting any response from the plugin. 
I tried the same steps above with this [firebase example app](https://github.com/firebase/quickstart-ios/tree/master/dynamiclinks), and I could see that my dynamic link configuration was working fine, getting a response.

Is there a way to test it under development? what am I missing? 

I am using a iPhone-X iOS 11.2.5 for testing and ionic 3

```cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.2 
    Node       : v6.11.3
    npm        : 3.10.10 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 
```

**Comment by Bengejd** [comment]
Probably a bit late, but I found this answer, but I haven't tested it yet personally, will report back...

> all a build of your app that includes the Dynamic Links or Branch SDK.
Generate a link and post it somewhere you can click it (meaning don’t enter it directly into the browser URL bar, because that comes with a bunch of other edge cases on both platforms).
Uninstall your app.
Open the link and let it redirect all the way through to the store page (if your app isn’t in the store, you can point the fallback URL anywhere else you want — it doesn’t matter).
Close the store.
Install a build of your app locally (using either Xcode/Android Studio, or TestFlight/Fabric/etc.)
Open your app.
The link data will be returned to you, exactly the same way it would be when your app is installed from the store by a user.

**Comment by chemerisuk** [comment]
Firebase Dynamic Links SDK has [unresolved bug](https://github.com/firebase/firebase-ios-sdk/issues/233) related to parsing `deepLink` for new app installs. It order to get it work your dynamic link MUST have [app preview page](https://firebase.google.com/docs/dynamic-links/link-previews), which is the default setting.
