### ISSUE TITLE
Add back `sendInvitation` / `getInvitation`?

### ISSUE THREAD

**Issue by adamduren** [chemerisuk/cordova-plugin-firebase-dynamiclinks#43]
Would you be opposed to adding back the `sendInvitation` and `getInvitation` methods? I'm curious as to why they were originally removed. I wouldn't mind doing the work to add them back if you are not opposed.

**Comment by chemerisuk** [comment]
Hey @adamduren. I decided to remove those methods because of two reasons:

1. Many iOS users do not have google account, so those invites do not work for them
2. I have very weird conflicts of the past google auth implementation and real-time database - the data has not received until force sign out
3. I like to keep things simple

Important to notice that there was not any issue in android implementation though. No idea what was the cause of issue in iOS.

I switched to native platform sharing instead of firebase invites for now.

**Comment by adamduren** [comment]
Makes sense. Thank you for the response. Closing.
